#!/usr/bin/env bash

minutes="${1:-"30"}"

active_containers="$(docker logs rcs_router 2>&1 | awk -v active=${minutes} '{t=(systime()-60*active); if ($2>t && $4=="docker_request:") {a[$5]=$5}} END {for (i in a){print i}}' ${LOG_FILE})"
all_containers="$(docker ps --all --filter label="dds" --format "{{.ID}}" || true)"

inactive_containers="$(diff \
  --unchanged-line-format= \
  --old-line-format='%L' \
  --new-line-format= \
  <(sort <<<"$all_containers") <(sort <<<"$active_containers")
)"

for c in $inactive_containers; do
  echo "remove inactive container: $c" >&2
  docker rm --force ${c}
done

echo "$inactive_containers"

