#!/usr/bin/env bash

minutes="${1:-"30"}"
: ${DYNAMIC_CONTAINER_LABEL:="dds"}

active_containers="$(docker logs rcs_router 2>&1 \
  | awk -v active=${minutes} \
  '{t=(systime()-60*active); if ($2>t && $4=="docker_request:") {a[$5]=$5}} END {for (i in a){print i}}' \
  )"
echo "$(date +%FT%T): active_containers: $active_containers" >&2
all_containers="$(docker ps --all --no-trunc --filter label="${DYNAMIC_CONTAINER_LABEL}" --format "{{.ID}}" || true)"
echo "$(date +%FT%T): all_containers: $all_containers" >&2

inactive_containers="$(diff \
  --unchanged-line-format= \
  --old-line-format='%L' \
  --new-line-format= \
  <(sort <<<"$all_containers") <(sort <<<"$active_containers")
)"
echo "$(date +%FT%T): inactive_containers:$inactive_containers" >&2

for c in $inactive_containers; do
  echo "$(date +%FT%T): remove inactive container: $c" >&2
  docker rm --force ${c}
done

echo "inactive_containers:$inactive_containers"

