#!/usr/bin/env bash

docker_repository="$1"
docker_version="${2:-"latest"}"
: ${DOCKER_NAMESPACE:="nasoym"}
: ${DYNAMIC_CONTAINER_LABEL:="dds"}

echo "$(date +%FT%T): launch container from repo: ${DOCKER_NAMESPACE}/${docker_repository}:${docker_version}" >&2

docker run \
  --detach \
  --publish-all \
  --label="${DYNAMIC_CONTAINER_LABEL}" \
  --label "${DOCKER_NAMESPACE}/${docker_repository}:${docker_version}" \
  ${DOCKER_NAMESPACE}/${docker_repository}:${docker_version}

