#!/usr/bin/env bash

: ${DOCKER_NAMESPACE:="nasoym"}
: ${PARALLEL_PULLS:="30"}
: ${DYNAMIC_CONTAINER_LABEL:="dds"}

echo "$(date +%FT%T): update all ${DOCKER_NAMESPACE} images" >&2

# docker images --filter "label=type=request_container" --format "{{.Repository}}:{{.Tag}}" nasoym/*
# docker images --filter "dangling=true" --format "{{.Repository}}:{{.Tag}}" nasoym/*

pulled_images="$(docker images --format "{{.Repository}}:{{.Tag}}" ${DOCKER_NAMESPACE}/* \
  | grep -v "<none>" \
  | parallel -L1 -j $PARALLEL_PULLS \
  "docker pull {} \
  | grep 'Downloaded newer image for ' \
  | sed 's/^.*Downloaded newer image for \\(.*\\)\$/\\1/g' \
  ")"

echo "$(date +%FT%T): pulled images: ${pulled_images}" >&2

for image in $pulled_images; do
  docker_container_id="$(docker ps --filter status=running --filter label="${image}" --filter label="${DYNAMIC_CONTAINER_LABEL}" --format "{{.ID}}" || true)"
  echo "$(date +%FT%T): found container for image: ${image} ${docker_container_id}" >&2
  if [[ -n "$docker_container_id" ]];then
    echo "$(date +%FT%T): relaunch container for image: ${image}" >&2
    docker run --detach --publish-all --label "${image}" --label="${DYNAMIC_CONTAINER_LABEL}" ${image} >&2 >/dev/null || true
  fi
done

dangling_images="$(docker images --filter dangling=true --format "{{.ID}} {{.Repository}}:{{.Tag}}")"
echo "$(date +%FT%T): delete dangling images: ${dangling_images}" >&2
echo "$dangling_images" | awk '{print $1}' | parallel --no-run-if-empty -L1 docker rmi

  # "docker pull {} | grep 'Downloaded newer image for nasoym/minimal_express:latest
echo "${pulled_images}"

