#!/usr/bin/env bash

docker_repository="$1"
docker_version="${2:-"latest"}"
: ${DOCKER_NAMESPACE:="nasoym"}
: ${DYNAMIC_CONTAINER_LABEL:="dds"}

echo "$(date +%FT%T): is running: ${DOCKER_NAMESPACE}/${docker_repository}:${docker_version}" >&2

docker ps \
  --latest \
  --filter status=running \
  --filter label="${DYNAMIC_CONTAINER_LABEL}" \
  --filter label="${DOCKER_NAMESPACE}/${docker_repository}:${docker_version}" \
  --no-trunc \
  --format "{{.ID}}"

